### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by amnesic** [safx/waifu2x-metal#1]
Tested with a MacBook Pro (17-inch, Early 2011) with OS X Sierra
`./waifu2x-metal Sample.jpg
fatal error: unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    waifu2x-metal                      0x000000010a0e8ae0 swift_reportError + 132
1    waifu2x-metal                      0x000000010a105e90 _swift_stdlib_reportFatalError + 61
2    waifu2x-metal                      0x0000000109e75930 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
3    waifu2x-metal                      0x000000010a075fc0 partial apply for (_fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never).(closure #2) + 109
4    waifu2x-metal                      0x0000000109e75930 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
5    waifu2x-metal                      0x000000010a030a10 specialized _fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never + 96
6    waifu2x-metal                      0x0000000109d9bf40 main + 176
7    libdyld.dylib                      0x00007fffb2668254 start + 1
Illegal instruction: 4`

**Comment by safx** [comment]
Your MBP does not seem to support Metal.
https://support.apple.com/en-us/HT205073
